In [1]:
import pandas as pd

g1 = pd.read_csv('../data/group1.csv')

In [4]:
g1

,Unnamed: 0,id,iid,pid,wave,gender,match,attr3_1,sinc3_1,intel3_1,fun3_1,amb3_1,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,group
0,2,1.0,1,13.0,1,0,1,6.0,8.0,8.0,8.0,7.0,19.00,18.00,19.00,18.00,14.00,1
1,10,2.0,2,11.0,1,0,0,7.0,5.0,8.0,10.0,3.0,35.00,20.00,20.00,20.00,0.00,1
2,11,2.0,2,12.0,1,0,0,7.0,5.0,8.0,10.0,3.0,60.00,0.00,0.00,40.00,0.00,1
3,13,2.0,2,14.0,1,0,1,7.0,5.0,8.0,10.0,3.0,30.00,5.00,15.00,40.00,5.00,1
4,15,2.0,2,16.0,1,0,0,7.0,5.0,8.0,10.0,3.0,50.00,0.00,30.00,10.00,0.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,2399,16.0,173,149.0,7,1,1,7.0,9.0,9.0,9.0,9.0,8.51,19.15,19.15,19.15,19.15,1
939,2400,16.0,173,150.0,7,1,0,7.0,9.0,9.0,9.0,9.0,12.00,20.00,20.00,20.00,14.00,1
940,2401,16.0,173,151.0,7,1,1,7.0,9.0,9.0,9.0,9.0,14.55,16.36,18.18,18.18,16.36,1
941,2404,16.0,173,154.0,7,1,1,7.0,9.0,9.0,9.0,9.0,15.38,17.31,17.31,17.31,17.31,1
942,2405,16.0,173,155.0,7,1,0,7.0,9.0,9.0,9.0,9.0,15.09,18.87,18.87,16.98,16.98,1